generatorName: go

gitHost: github.com
gitUserId: TobiPeterG
gitRepoId: go-nautobot

packageName: nautobot

globalProperty:
  apiDocs: true
  modelDocs: true
  apiTests: true
  modelTests: true

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: "false"
  packageVersion: "3"
  enumClassPrefix: true
